name: "Validate Flux Helm Release"
description: "Github Action to validate Flux Helm Releases with kubeval"
author: "SupplyPike"
branding:
  icon: "check-square"
  color: "blue"
inputs:
  helmRelease:
    description: "The HelmRelease YAML file path or dir"
    required: true
  ignoreValues:
    description: "When set to true HelmRelease values will be ignored"
    default: "false"
    required: false
  kubernetesVersion:
    description: "Version of Kubernetes to validate against"
    default: "master"
    required: true
outputs:
  numFilesTested:
    description: The number of HelmRelease files which were tested

runs:
  using: "node12"
  main: "dist/index.js"
