name: CI

on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Helm Release from Helm Repo
        uses: ./
        with:
          helmRelease: test/flagger.yaml
          kubernetesVersion: 1.16.0
      - name: Validate Helm Release from Git Repo
        uses: ./
        with:
          helmRelease: test/podinfo.yaml
      - name: Validate Helm Release without values
        uses: ./
        with:
          helmRelease: test/podinfo.yaml
          ignoreValues: true
  test-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate all Helm Releases in the test dir
        id: validate-dir
        uses: ./
        with:
          helmRelease: test/
      - name: Check tested file count
        env:
          NUM_FILES_TESTED: ${{ steps.validate-dir.outputs.numFilesTested }}
        run: "(( NUM_FILES_TESTED==3 ))"
  test-excluded-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate all Helm Releases in the test dir
        id: validate-dir
        uses: ./
        with:
          helmRelease: test/
          excludedReleases: |
            test/subdirectory/ghost.yaml
            test/flagger.yaml
      - name: Check tested file count
        env:
          NUM_FILES_TESTED: ${{ steps.validate-dir.outputs.numFilesTested }}
        run: "(( NUM_FILES_TESTED==1 ))"
